title: Data Science 2019
logo: /assets/img/LIP-black-1000x677.png
description: > # this means to ignore newlines until "show_downloads:"
  Data Science symposium guide.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: https://lip-computing.github.io
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
- .gitignore
- .jekyll-cache
- README.md
